name: ORBIT07 - Open (08:55 TPE)

on:
  schedule:
    - cron: '55 0 * * 1-5'    # UTC 00:55 = TPE 08:55
  workflow_dispatch: {}

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: POST /cron/open
        run: |
          set -e
          curl -fsS --retry 3 --retry-delay 5 --max-time 25 \
            -X POST "$BASE_URL/cron/open?key=$CRON_KEY"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_KEY:  ${{ secrets.CRON_KEY }}
