name: ORBIT07 - Open (08:55 TPE)

# ← 新增這兩段（與 name / on 同層級）
permissions: {}
concurrency:
  group: open-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '55 0 * * 1-5'    # UTC 00:55 = TPE 08:55（週一到週五）
  workflow_dispatch: {}

jobs:
  call:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: POST /cron/open
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_KEY:  ${{ secrets.CRON_KEY }}
        run: |
          set -e
          curl -fsS --retry 3 --retry-delay 5 --max-time 25 \
            -X POST "$BASE_URL/cron/open?key=$CRON_KEY"
