name: ORBIT07 - Morning (07:20 TPE)

on:
  schedule:
    - cron: '20 23 * * 1-5'   # UTC 23:20 = TPE 07:20（週一到週五）
  workflow_dispatch: {}

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: POST /cron/morning
        run: |
          set -e
          curl -fsS --retry 3 --retry-delay 5 --max-time 25 \
            -X POST "$BASE_URL/cron/morning?key=$CRON_KEY"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_KEY:  ${{ secrets.CRON_KEY }}
