name: test-webhook
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'endpoint'
        default: 'cron/ping'
      body:
        description: 'JSON body'
        default: '{"msg":"hello from Actions"}'

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Show variables (BASE_URL only)
        env:
          BASE_URL: ${{ vars.BASE_URL }}
        run: |
          echo "BASE_URL=$BASE_URL"
          if [ -z "$BASE_URL" ]; then
            echo "❌ BASE_URL 沒有設定（Repo → Settings → Secrets and variables → Actions → Variables）" && exit 1
          fi

      - name: Health check
        env:
          BASE_URL: ${{ vars.BASE_URL }}
        run: |
          echo "GET $BASE_URL/health"
          curl -sS -i "$BASE_URL/health" | sed -n '1,40p'

      - name: Call webhook
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}
          PATH:     ${{ github.event.inputs.path }}
          BODY:     ${{ github.event.inputs.body }}
        run: |
          if [ -z "$CRON_KEY" ]; then
            echo "❌ CRON_KEY 沒有設定（Repo → Settings → Secrets and variables → Actions → Secrets）" && exit 1
          fi
          echo "POST $BASE_URL/$PATH"
          http_code=$(curl -sS -o response.json -w "%{http_code}" \
            -X POST "$BASE_URL/$PATH?key=$CRON_KEY" \
            -H "Content-Type: application/json" \
            -d "$BODY")
          echo "HTTP $http_code"; echo "=== Response ==="; cat response.json
          test "$http_code" -lt 400
