name: keep-alive

on:
  # 台北 07:00–14:00（週一～五）→ UTC 23:00–06:59
  schedule:
    - cron: "*/10 23,0-6 * * 1-5"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: keep-alive
      cancel-in-progress: true
    env:
      BASE: https://orbit07-webhook.onrender.com
      CHAT_ID: "8418229161"   # 你的 chat_id（讓 /lists/watch 也被喚醒）
    steps:
      - name: Warm up endpoints
        run: |
          set -e
          for PATH in \
            "/healthz" \
            "/lists/ping" \
            "/lists/watch?chat_id=${CHAT_ID}&format=md" \
            "/intl/market_snapshot"
          do
            echo "GET $BASE$PATH"
            curl -fsS "$BASE$PATH" || true
          done
